### ISSUE TITLE
Loss of performance

### ISSUE THREAD

**Issue by NullVerdict** [wagesj45/MercuryAlloy#1]
After cross compilation, I noticed that the browser became worse to pass the test Speedometer 3.0, readings fell from 9 to 7, any idea why this could happen? I also want to know why PGO doesn't work during cross compilation?

**Comment by wagesj45** [comment]
These questions might be better posed over at the [Mercury browser repository](https://github.com/Alex313031/Mercury). This project just provides the scripts to automate the build.

To directly answer your questions, though, the last time I successfully built Mercury there was a bug in Mercury that would utilize CPU cores at 100% doing nothing, which very well might impact performance on Speedometer 3.0. I do not know anything about `PGO` and what it does and why it might not work with cross compilation.

**Comment by NullVerdict** [comment]
> These questions might be better posed over at the [Mercury browser repository](https://github.com/Alex313031/Mercury). This project just provides the scripts to automate the build.
> 
> To directly answer your questions, though, the last time I successfully built Mercury there was a bug in Mercury that would utilize CPU cores at 100% doing nothing, which very well might impact performance on Speedometer 3.0. I do not know anything about `PGO` and what it does and why it might not work with cross compilation.

I'd be interested in hearing your thoughts on this. Could you please share the Mercury version you're using? I'd like to compare it with mine.

**Comment by wagesj45** [comment]
Tonight I was able to build v127.0.1 and applied a fix for the CPU usage bug. [You can download my build here](https://jordanwages.com/browser/mercurybrowser-127.0.1.en-US.win64.installer.exe). **It should go without saying be careful of download random executable files online.** You should be able to recreate it yourself with the latest commit of this repository.

Even with the CPU fix, I get slower speeds than Firefox 127.0 on various benchmarks. I do not know why, but this [seems to be a known thing](https://www.phoronix.com/review/mercury-firefox-perf). It is possible that the performance gains possible with Mercury are highly hardware and OS dependent, as the [author's performance testing took place on Ubuntu using an AMD FX series CPU](https://thorium.rocks/mercury_performance), whereas I'm building for Windows using an AMD Threadripper.

![comparison](https://github.com/wagesj45/MercuryAlloy/assets/2460850/f0392d3b-af8a-44cf-9e1a-0e334a63c5f3)

**Comment by NullVerdict** [comment]
> Tonight I was able to build v127.0.1 and applied a fix for the CPU usage bug. [You can download my build here](https://jordanwages.com/browser/mercurybrowser-127.0.1.en-US.win64.installer.exe). **It should go without saying be careful of download random executable files online.** You should be able to recreate it yourself with the latest commit of this repository.
> 
> Even with the CPU fix, I get slower speeds than Firefox 127.0 on various benchmarks. I do not know why, but this [seems to be a known thing](https://www.phoronix.com/review/mercury-firefox-perf). It is possible that the performance gains possible with Mercury are highly hardware and OS dependent, as the [author's performance testing took place on Ubuntu using an AMD FX series CPU](https://thorium.rocks/mercury_performance), whereas I'm building for Windows using an AMD Threadripper.
> 
> ![comparison](https://private-user-images.githubusercontent.com/2460850/340594799-f0392d3b-af8a-44cf-9e1a-0e334a63c5f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MDgwMDksIm5iZiI6MTcxODcwNzcwOSwicGF0aCI6Ii8yNDYwODUwLzM0MDU5NDc5OS1mMDM5MmQzYi1hZjhhLTQ0Y2YtOWUxYS0wZTMzNGE2M2M1ZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTA0ODI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQxZTFlOGI0MmJiNjJiODEzNmNiZjY0MDViOTgwY2ZhYWRmZTQ3OWZlNTQ4YjU5NmRkZmJkZGIwMTk2NzFlYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.V54DiUvL1RIsPbcGUbHjCutnxagExQ68g_kIQQ4bZmM)

Tested it, and it's almost identical to my build. This might indeed be a cross-compilation issue. At least Mercury for Windows builds directly on Windows, so building on Windows might avoid these performance problems. However, it's puzzling that Official Firefox Nightly, which is built on Linux, works perfectly well. There could be a bug somewhere.
